name: 'dbt_databricks_demo'

config-version: 2
version: '0.1'

profile: 'dbt_databricks_demo'

model-paths: ["models"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

tests:
  dbt_databricks_demo:
    +as_columnstore: False

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  dbt_databricks_demo:
      materialized: table
      as_columnstore: False
      staging:
        materialized: view
        as_columnstore: False
