dbt_databricks_demo:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: drewfurg-sql.database.windows.net
      port: 1433
      database: sql-dev
      schema: dbt_dev
      user: {{env_var('SQL_USERNAME')}}
      password: {{env_var('SQL_PASSWORD')}}
    prod:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: drewfurg-sql.database.windows.net
      port: 1433
      database: sql-prod
      schema: dbt_prod
      user: {{env_var('SQL_USERNAME')}}
      password: {{env_var('SQL_PASSWORD')}}